# Generated by Django 6.0.3 on 2026-03-18 02:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Robótica 10A, Informática 11B', max_length=100)),
                ('grado', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_estudiantes/')),
                ('activo', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='gestion.curso')),
            ],
        ),
        migrations.CreateModel(
            name='SesionClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('numero_clase', models.PositiveIntegerField(help_text='Número de la clase en el periodo/año')),
                ('tema', models.CharField(help_text='Tema tratado hoy', max_length=255)),
                ('actividad_realizada', models.BooleanField(default=False, help_text='¿Hubo actividad evaluable hoy?')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='gestion.curso')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Anotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COMPORTAMIENTO', 'Comportamiento (Positivo/Negativo)'), ('MATERIALES', 'Falta de materiales'), ('PARTICIPACION', 'Participación destacada'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotaciones', to='gestion.estudiante')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotaciones', to='gestion.sesionclase')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('EXCUSADO', 'Tiene Excusa')], default='PRESENTE', max_length=10)),
                ('motivo_excusa', models.TextField(blank=True, help_text='Opcional: Por qué faltó', null=True)),
                ('completo_actividad', models.BooleanField(default=False)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_asistencia', to='gestion.estudiante')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='gestion.sesionclase')),
            ],
            options={
                'unique_together': {('sesion', 'estudiante')},
            },
        ),
    ]
