# Generated by Django 6.0.3 on 2026-04-01 23:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_estudiantes/')),
                ('activo', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='gestion.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('nivel', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'unique_together': {('numero', 'nivel')},
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='gestion.grado'),
        ),
        migrations.CreateModel(
            name='CursoMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso_materias', to='gestion.curso')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso_materias', to='gestion.materia')),
            ],
            options={
                'unique_together': {('curso', 'materia')},
            },
        ),
        migrations.CreateModel(
            name='SesionClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.IntegerField(choices=[(1, 'Primer Periodo'), (2, 'Segundo Periodo'), (3, 'Tercer Periodo'), (4, 'Cuarto Periodo')], default=1)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('numero_clase', models.PositiveIntegerField(help_text='Número de la clase en el periodo/año')),
                ('tema', models.CharField(max_length=255)),
                ('actividad_realizada', models.BooleanField(default=False)),
                ('tarea_asignada', models.TextField(blank=True, null=True)),
                ('realizo_quiz', models.BooleanField(default=False)),
                ('realizo_examen', models.BooleanField(default=False)),
                ('curso_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='gestion.cursomateria')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('curso_materia', 'periodo', 'numero_clase')},
            },
        ),
        migrations.CreateModel(
            name='Anotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COMPORTAMIENTO', 'Comportamiento (Positivo/Negativo)'), ('MATERIALES', 'Falta de materiales'), ('PARTICIPACION', 'Participación destacada'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotaciones', to='gestion.estudiante')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotaciones', to='gestion.sesionclase')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('grado', 'seccion')},
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('EXCUSADO', 'Tiene Excusa')], default='PRESENTE', max_length=10)),
                ('motivo_excusa', models.TextField(blank=True, help_text='Opcional: Por qué faltó', null=True)),
                ('entrego_tarea', models.BooleanField(default=False)),
                ('evidencia_foto', models.ImageField(blank=True, null=True, upload_to='evidencias/%Y/%m/')),
                ('completo_actividad', models.BooleanField(default=False)),
                ('calificacion', models.IntegerField(blank=True, null=True)),
                ('comentario_actividad', models.TextField(blank=True, null=True)),
                ('calificacion_tarea', models.IntegerField(blank=True, null=True)),
                ('comentario_tarea', models.TextField(blank=True, null=True)),
                ('realizo_quiz', models.BooleanField(default=False)),
                ('calificacion_quiz', models.IntegerField(blank=True, null=True)),
                ('comentario_quiz', models.TextField(blank=True, null=True)),
                ('realizo_examen', models.BooleanField(default=False)),
                ('calificacion_examen', models.IntegerField(blank=True, null=True)),
                ('comentario_examen', models.TextField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_asistencia', to='gestion.estudiante')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='gestion.sesionclase')),
            ],
            options={
                'unique_together': {('sesion', 'estudiante')},
            },
        ),
    ]
