# Generated by Django 6.0.3 on 2026-03-18 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Robótica, Informática', max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='curso',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='curso',
            name='grado',
            field=models.CharField(default=1, help_text='Ej: 10A, 11B', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='materia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='gestion.materia'),
        ),
    ]
