# Generated by Django 6.0.3 on 2026-04-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grado',
            options={'ordering': ['numero']},
        ),
        migrations.AlterUniqueTogether(
            name='grado',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='grado',
            name='numero',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.RemoveField(
            model_name='grado',
            name='nivel',
        ),
    ]
