# Generated by Django 6.0.3 on 2026-04-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_grado_options_alter_grado_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='seccion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
