# Generated by Django 6.0.3 on 2026-03-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_materia_remove_curso_nombre_alter_curso_grado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionclase',
            name='periodo',
            field=models.IntegerField(choices=[(1, 'Primer Periodo'), (2, 'Segundo Periodo'), (3, 'Tercer Periodo'), (4, 'Cuarto Periodo')], default=1),
        ),
        migrations.AlterUniqueTogether(
            name='sesionclase',
            unique_together={('curso', 'periodo', 'numero_clase')},
        ),
    ]
