# Generated by Django 6.0.3 on 2026-03-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_sesionclase_periodo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionclase',
            name='tarea_asignada',
            field=models.TextField(blank=True, help_text='Tarea o pendiente para la próxima clase', null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='grado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
