# Generated by Django 6.0.3 on 2026-03-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_sesionclase_tarea_asignada_alter_curso_grado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='entrego_tarea',
            field=models.BooleanField(default=False),
        ),
    ]
