# Generated by Django 6.0.3 on 2026-03-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_asistencia_entrego_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='evidencia_foto',
            field=models.ImageField(blank=True, null=True, upload_to='evidencias/%Y/%m/'),
        ),
    ]
