# Generated by Django 6.0.3 on 2026-03-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_asistencia_evidencia_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='calificacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='comentario_actividad',
            field=models.TextField(blank=True, null=True),
        ),
    ]
