# Generated by Django 6.0.3 on 2026-03-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_asistencia_calificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='calificacion_tarea',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='comentario_tarea',
            field=models.TextField(blank=True, null=True),
        ),
    ]
