# Generated by Django 6.0.3 on 2026-03-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_asistencia_calificacion_tarea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='calificacion_examen',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='calificacion_quiz',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='comentario_examen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='comentario_quiz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='realizo_examen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='realizo_quiz',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sesionclase',
            name='realizo_examen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sesionclase',
            name='realizo_quiz',
            field=models.BooleanField(default=False),
        ),
    ]
